services:
  globetrotter:
    build: .
    container_name: globetrotter_app
    ports:
      - "4000:4000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - PORT=4000
